"""empty message

Revision ID: 07ea68c170a2
Revises: 
Create Date: 2023-04-07 01:46:59.939705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ea68c170a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'progress', 'plans', 'complete', name='reportstatus'), nullable=False),
    sa.Column('progress', sa.String(), nullable=False),
    sa.Column('plans', sa.String(), nullable=False),
    sa.Column('blockers', sa.String(), nullable=True),
    sa.Column('message_timestamp', sa.String(), nullable=True),
    sa.Column('report_timestamp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('users')
    # ### end Alembic commands ###
