"""empty message

Revision ID: 2a5588a09aad
Revises: 51c6bdd632b9
Create Date: 2023-04-07 23:54:21.423500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5588a09aad'
down_revision = '51c6bdd632b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
