"""empty message

Revision ID: 51c6bdd632b9
Revises: e4cf7eecb9b4
Create Date: 2023-04-07 23:54:14.787938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c6bdd632b9'
down_revision = 'e4cf7eecb9b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
