"""empty message

Revision ID: 60c32395a609
Revises: 3f1e73110198
Create Date: 2023-04-07 23:50:43.614009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60c32395a609'
down_revision = '3f1e73110198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latest_question_ts', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('not_started', 'progress', 'plans', 'complete', name='reportstatus'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plans', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blockers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_timestamp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('report_timestamp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reports_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    # ### end Alembic commands ###
